/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUtUalNHVkNZeXVhSjVoSTNqMWJiSi9tN2dZc0dnTFNXM2l5ZUl2YnUxQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSVp5T2NZMkpLN2ZtNGZ0ZlZkNm4vSllCdCs4dStVazdDVnQ2WGU3aHUyTT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4TWxPclo1cjczNFYya3pwZzFWWER0dUgvb0dSS2hQWDJ3TnNuODZRcDNnPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBWS91d3FQZlRzblk1cmFJY1ZtVVQxRytFRjQwendIR2FvNld4RjhHMVJZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1FRjVsV2xva1lSWTdUa0ZvYUhISFZIWFk5MmFhSjYvY2hKMjhsSndWMVE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkM2eG1pMmYxZ0FTcmR4OUYzb3RKSjNlOFNvR0NWdnZ6L3RLMGZhS3dwV0k9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia05KSEpjK0RQZWw3dW92Z3pPOWNISDdteXBlNHZLamNwa0dTNzlZMUlVbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSExhR1JYMGIyVFlsb1dicUxWS2VyZEZqaUNrS3A2STZ3RFYvM0RaenFHTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNiSmtOZWZpaitrRTZKV0FIaUdGN2lvUW1WOGp6eEt5UGtQeGV2TGUzK3NpSnB5NzRRYXM0SjZSbDFVL0xPcUcydHNoUm9NaVh6TTBSSUVacWJDTkN3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NTQsImFkdlNlY3JldEtleSI6IjQrUmZXL2t5bHlTR0dRT0RoV3lubXAwZzMrNWJCSk5hRDdDdjRqU3F4NFE9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6Ilo3VzdHUnB1UVFhVVYxTkhOQVRQSXciLCJwaG9uZUlkIjoiNzE2OTVkMTYtMDI1Ny00MjFhLWI0YjMtNTVmYWY5Y2QzYmYyIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdIQnBRdEp3a01Pc1ZLQUtlWVkwd2xlOXphOD0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJqQ0h4QXlWcTBCRXN4MG12d1JXeW9nWGhFNkk9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiUkpISEFWR0UiLCJtZSI6eyJpZCI6IjI2MzcxNjcyOTIyMjo3NkBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTWFTaCswQkVKYVB0cmtHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiTm5zSE1sMi9uelZ3SHRsTWxhM3h3Vk9HZkpURXpQSi9tUENCWnRYY3pDZz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiY0ExUndLOVJDWjZ4bGZVMU52NndqWFZOQzRIaitldGdRUmg0UUlzTC8rcHFsaWVIK2FrSCtobkRDcnh0cmlPY0lSRGFBWFp6eEc1dVNZZmoyY3dPQWc9PSIsImRldmljZVNpZ25hdHVyZSI6IlRQNVpnbVE5cWtUa3ZZc0ZHb3JYWmZRYkFuUHZWcEZ1Mk42K0ZkYVAwMkt4ZjJTVFNRbk5VQkFJZHRXVjkxU29pQWllOTdwNUVVcnc5Zno3Z1pxK0RnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjYzNzE2NzI5MjIyOjc2QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlRaN0J6SmR2NTgxY0I3WlRKV3Q4Y0ZUaG55VXhNenlmNWp3Z1diVjNNd28ifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzEwMzcwOTF9';

const prefix = process.env.PREFIX || '+';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'MamboJosh';
const packname = process.env.PACKNAME || 'MamboJosh';
const dev = process.env.DEV || '263716729222';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'Joshuamambo';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
